[package]
name = "practicas"
version = "0.1.0"
authors = ["Juan Oca√±a <juanov98@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
na = { package = "nalgebra", version = "*" }
